insert into ciudad(id_estado,nombreCiudad) values(1,"Acacoyagua"),
(1,"Acala"),
(1,"Acapetahua"),
(1,"Altamirano"),
(1,"Amatán"),
(1,"Amatenango de la Frontera"),
(1,"Amatenango del Valle"),
(1,"Ángel Albino Corzo"),
(1,"Arriaga"),
(1,"Bejucal de Ocampo"),
(1,"Bella Vista"),
(1,"Berriozábal"),
(1,"Bochil"),
(1,"El Bosque"),
(1,"Cacahoatán"),
(1,"Catazajá"),
(1,"Cintalapa"),
(1,"Coapilla"),
(1,"Comitán de Domínguez"),
(1,"La Concordia"),
(1,"Copainalá"),
(1,"Chalchihuitán"),
(1,"Chamula"),
(1,"Chanal"),
(1,"Chapultenango"),
(1,"Chenalhó"),
(1,"Chiapa de Corzo"),
(1,"Chiapilla"),
(1,"Chicoasén"),
(1,"Chicomuselo"),
(1,"Chilón"),
(1,"Escuintla"),
(1,"Francisco León"),
(1,"Frontera Comalapa"),
(1,"Frontera Hidalgo"),
(1,"La Grandeza"),
(1,"Huehuetán"),
(1,"Huixtán"),
(1,"Huitiupán"),
(1,"Huixtla"),
(1,"La Independencia"),
(1,"Ixhuatán"),
(1,"Ixtacomitán"),
(1,"Ixtapa"),
(1,"Ixtapangajoya"),
(1,"Jiquipilas"),
(1,"Jitotol"),
(1,"Juárez"),
(1,"Larráinzar"),
(1,"La Libertad"),
(1,"Mapastepec"),
(1,"Las Margaritas"),
(1,"Mazapa de Madero"),
(1,"Mazatán"),
(1,"Metapa"),
(1,"Mitontic"),
(1,"Motozintla"),
(1,"Nicolás Ruíz"),
(1,"Ocosingo"),
(1,"Ocotepec"),
(1,"Ocozocoautla de Espinosa"),
(1,"Ostuacán"),
(1,"Osumacinta"),
(1,"Oxchuc"),
(1,"Palenque"),
(1,"Pantelhó"),
(1,"Pantepec"),
(1,"Pichucalco"),
(1,"Pijijiapan"),
(1,"El Porvenir"),
(1,"Villa Comaltitlán"),
(1,"Pueblo Nuevo Solistahuacán"),
(1,"Rayón"),
(1,"Reforma"),
(1,"Las Rosas"),
(1,"Sabanilla"),
(1,"Salto de Agua"),
(1,"San Cristóbal de las Casas"),
(1,"San Fernando"),
(1,"Siltepec"),
(1,"Simojovel"),
(1,"Sitalá"),
(1,"Socoltenango"),
(1,"Solosuchiapa"),
(1,"Soyaló"),
(1,"Suchiapa"),
(1,"Suchiate"),
(1,"Sunuapa"),
(1,"Tapachula"),
(1,"Tapalapa"),
(1,"Tapilula"),
(1,"Tecpatán"),
(1,"Tenejapa"),
(1,"Teopisca"),
(1,"Tila"),
(1,"Tonalá"),
(1,"Totolapa"),
(1,"La Trinitaria"),
(1,"Tumbalá"),
(1,"Tuxtla Gutiérrez"),
(1,"Tuxtla Chico"),
(1,"Tuzantán"),
(1,"Tzimol"),
(1,"Unión Juárez"),
(1,"Venustiano Carranza"),
(1,"Villa Corzo"),
(1,"Villaflores"),
(1,"Yajalón"),
(1,"San Lucas"),
(1,"Zinacantán"),
(1,"San Juan Cancuc"),
(1,"Aldama"),
(1,"Benemérito de las Américas"),
(1,"Maravilla Tenejapa"),
(1,"Marqués de Comillas"),
(1,"Montecristo de Guerrero"),
(1,"San Andrés Duraznal"),
(1,"Santiago el Pinar"),
(1,"Belisario Domínguez"),
(1,"Emiliano Zapata"),
(1,"El Parral"),
(1,"Mezcalapa");